import type { Metadata } from 'next';
import './globals.css';

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className="text-xxs xs:text-xs sm:text-sm md:text-base lg:text-lg xl:text-xl 2xl:text-2xl overflow-x-hidden">
				{children}
			</body>
		</html>
	);
}
